# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('searched_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('uri', models.CharField(max_length=100, null=True)),
                ('songs', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
